// <auto-generated />
namespace RegistrationForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class alterDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201406051821244_alterDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
